interface SeedColor {
  name: string;
  hex: string;
}

export const colors: SeedColor[] = [
  { name: 'Blanco', hex: '#ffffff' },
  { name: 'Negro', hex: '#000000' },
  { name: 'Gris', hex: '#808080' },
  { name: 'Rojo', hex: '#ff0000' },
  { name: 'Azul', hex: '#0000ff' },
  { name: 'Verde', hex: '#008000' },
  { name: 'Azul Marino', hex: '#000080' },
  { name: 'Amarillo', hex: '#ffff00' },
  { name: 'Gris Oscuro', hex: '#a9a9a9' },
  { name: 'Gris Claro', hex: '#d3d3d3' },
  { name: 'Rosa', hex: '#ffc0cb' },
  { name: 'Verde Musgo', hex: '#8a9a5b' },
  { name: 'Azul Oscuro', hex: '#00008b' },
  { name: 'Naranja', hex: '#ffa500' },
  { name: 'Beige', hex: '#f5f5dc' },
  { name: 'Fucsia', hex: '#ff00ff' },
  { name: 'Crema', hex: '#ffffc0' },
  { name: 'Azul Claro', hex: '#add8e6' },
  { name: 'Verde Claro', hex: '#90ee90' },
  { name: 'Plata', hex: '#c0c0c0' },
  { name: 'Burgundy', hex: '#800020' },
  { name: 'Marrón', hex: '#a52a2a' },
  { name: 'Azul Petróleo', hex: '#009b8a' },
  { name: 'Lila', hex: '#c8a2c8' },
  { name: 'Coral', hex: '#ff7f50' },
  { name: 'Verde Oscuro', hex: '#006400' },
  { name: 'Ocre', hex: '#cc7722' },
  { name: 'Azul Acero', hex: '#4682b4' },
  { name: 'Rosa Claro', hex: '#ffb6c1' },
  { name: 'Naranja Claro', hex: '#ffa500' },
  { name: 'Violeta', hex: '#ee82ee' },
  { name: 'Verde Limón', hex: '#98fb98' },
  { name: 'Oro', hex: '#ffd700' },
  { name: 'Gamuza', hex: '#cd853f' },
  { name: 'Rosa Chicle', hex: '#ff6eff' },
  { name: 'Naranja Oscuro', hex: '#ff8c00' },
  { name: 'Turquesa', hex: '#40e0d0' },
  { name: 'Terracota', hex: '#ca6641' },
  { name: 'Lavanda', hex: '#e6e6fa' },
  { name: 'Coral Claro', hex: '#f08080' },
  { name: 'Marrón Claro', hex: '#b0b090' },
  { name: 'Oro Claro', hex: '#d3d3b0' },
  { name: 'Oro Oscuro', hex: '#b8860b' },
  { name: 'Caqui', hex: '#bdb76b' },
  { name: 'Violeta Oscuro', hex: '#9400d3' },
];
