interface SeedCity {
  name: string;
  provinceId: string;
}

export const chacoCities: SeedCity[] = [
  { name: 'Aviá Teraí', provinceId: 'CHA' },
  { name: 'Barranqueras', provinceId: 'CHA' },
  { name: 'Basail', provinceId: 'CHA' },
  { name: 'Campo Largo', provinceId: 'CHA' },
  { name: 'Capitán solari', provinceId: 'CHA' },
  { name: 'Charadai', provinceId: 'CHA' },
  { name: 'Charata', provinceId: 'CHA' },
  { name: 'Chorotis', provinceId: 'CHA' },
  { name: 'Ciervo Petiso', provinceId: 'CHA' },
  { name: 'Colonia Aborigen', provinceId: 'CHA' },
  { name: 'Colonia Benítez', provinceId: 'CHA' },
  { name: 'Colonia Elisa', provinceId: 'CHA' },
  { name: 'Colonias Unidas', provinceId: 'CHA' },
  { name: 'Coronel Du Graty', provinceId: 'CHA' },
  { name: 'Corzuela', provinceId: 'CHA' },
  { name: 'Cote Lai', provinceId: 'CHA' },
  { name: 'El Espinillo', provinceId: 'CHA' },
  { name: 'El Sauzalito', provinceId: 'CHA' },
  { name: 'Enrique Urién', provinceId: 'CHA' },
  { name: 'Fontana', provinceId: 'CHA' },
  { name: 'Fuerte Esperanza', provinceId: 'CHA' },
  { name: 'Gancedo', provinceId: 'CHA' },
  { name: 'General Capdevilla', provinceId: 'CHA' },
  { name: 'General José de San Martín', provinceId: 'CHA' },
  { name: 'General Pinedo', provinceId: 'CHA' },
  { name: 'General Vedia', provinceId: 'CHA' },
  { name: 'Hermoso Campo', provinceId: 'CHA' },
  { name: 'Isla del Cerrito', provinceId: 'CHA' },
  { name: 'Juan José Castelli', provinceId: 'CHA' },
  { name: 'La Clotilde', provinceId: 'CHA' },
  { name: 'El Eduvigis', provinceId: 'CHA' },
  { name: 'La Escondida', provinceId: 'CHA' },
  { name: 'La Leonesa', provinceId: 'CHA' },
  { name: 'La Tigra', provinceId: 'CHA' },
  { name: 'La Verde', provinceId: 'CHA' },
  { name: 'Laguna Blanca', provinceId: 'CHA' },
  { name: 'Laguna Limpia', provinceId: 'CHA' },
  { name: 'Lapachito', provinceId: 'CHA' },
  { name: 'Las Breñas', provinceId: 'CHA' },
  { name: 'Las Garcitas', provinceId: 'CHA' },
  { name: 'Las Palmas', provinceId: 'CHA' },
  { name: 'Los Frentones', provinceId: 'CHA' },
  { name: 'Machagai', provinceId: 'CHA' },
  { name: 'Makallé', provinceId: 'CHA' },
  { name: 'Margarita Belén', provinceId: 'CHA' },
  { name: 'Miraflores', provinceId: 'CHA' },
  { name: 'Misión Nueva Pompeya', provinceId: 'CHA' },
  { name: 'Napenay', provinceId: 'CHA' },
  { name: 'Pampa Almirón', provinceId: 'CHA' },
  { name: 'Pampa del Indio', provinceId: 'CHA' },
  { name: 'Pampa del Infierno', provinceId: 'CHA' },
  { name: 'Presidencia de la Plaza', provinceId: 'CHA' },
  { name: 'Presidencia Roca', provinceId: 'CHA' },
  { name: 'Presidencia Roque Sáenz Peña', provinceId: 'CHA' },
  { name: 'Puerto Bermejo', provinceId: 'CHA' },
  { name: 'Puero Eva Perón', provinceId: 'CHA' },
  { name: 'Puerto Tirol', provinceId: 'CHA' },
  { name: 'Puerto Vilelas', provinceId: 'CHA' },
  { name: 'Quitilipi', provinceId: 'CHA' },
  { name: 'Resistencia', provinceId: 'CHA' },
  { name: 'Samuhú', provinceId: 'CHA' },
  { name: 'San Bernardo', provinceId: 'CHA' },
  { name: 'Santa Sylvina', provinceId: 'CHA' },
  { name: 'Taco Pozo', provinceId: 'CHA' },
  { name: 'Tres Isletas', provinceId: 'CHA' },
  { name: 'Villa Berthet', provinceId: 'CHA' },
  { name: 'Villa Río Bermejito', provinceId: 'CHA' },
  { name: 'Villa Ángela', provinceId: 'CHA' },
];
