import bcryptjs from 'bcryptjs';
import { nanoid } from '../utils';

interface SeedProduct {
  id: string;
  description: string;
  images: string[];
  inStock: number;
  price: number;
  slug: string;
  tags: string[];
  title: string;
  type: ValidTypes;
  brand: string;
}

interface SeedBrand {
  id: string;
  name: string;
  slug: string;
}

interface SeedUser {
  id: string;
  name: string;
  lastName: string;
  userName: string;
  email: string;
  dni: string;
  password: string;
  role: 'admin' | 'user' | 'salesman';
  phone: string;
}

interface SeedCategory {
  id?: number;
  name: string;
}

type ValidTypes = 'smartphone' | 'laptop' | 'tablet' | 'accessory';

interface SeedData {
  users: SeedUser[];
  categories: SeedCategory[];
  products: SeedProduct[];
  brands: SeedBrand[];
}

export const initialData: SeedData = {
  users: [
    {
      id: nanoid(11),
      email: 'alex@google.com',
      name: 'Alex',
      lastName: 'Oliva',
      password: bcryptjs.hashSync('123456'),
      role: 'admin',
      userName: '12345678',
      dni: '12345678',
      phone: '3644123456',
    },
    {
      id: nanoid(11),
      email: 'invitado@google.com',
      name: 'Invitado',
      lastName: 'Invitado',
      password: bcryptjs.hashSync('123456'),
      role: 'user',
      userName: '3213123x',
      dni: '12343278',
      phone: '3644123456',
    },
    {
      id: nanoid(11),
      email: 'juan@google.com',
      name: 'Juan',
      lastName: 'Perez',
      password: bcryptjs.hashSync('123456'),
      role: 'user',
      userName: '22345678',
      dni: '22345678',
      phone: '3644123456',
    },
    {
      id: nanoid(11),
      email: 'fulano@google.com',
      name: 'Fulano de',
      lastName: 'Tal',
      password: bcryptjs.hashSync('123456'),
      role: 'user',
      userName: '32345678',
      dni: '32345678',
      phone: '3644123456',
    },
    {
      id: nanoid(11),
      email: 'marcos@email.com',
      name: 'Marcos',
      lastName: 'Rodriguez',
      password: bcryptjs.hashSync('123456'),
      role: 'user',
      userName: '42345678',
      dni: '42345678',
      phone: '3644123456',
    },
    {
      id: nanoid(11),
      email: 'matias@email.com',
      name: 'Matias',
      lastName: 'DLF',
      password: bcryptjs.hashSync('123456'),
      role: 'admin',
      userName: '52345678',
      dni: '52345678',
      phone: '3644123456',
    },
    {
      id: nanoid(11),
      email: 'emma@email.com',
      name: 'Emma',
      lastName: 'Smith',
      password: bcryptjs.hashSync('123456'),
      role: 'user',
      userName: '62345678',
      dni: '62345678',
      phone: '3644123456',
    },
    {
      id: nanoid(11),
      email: 'john@email.com',
      name: 'John',
      lastName: 'Doe',
      password: bcryptjs.hashSync('123456'),
      role: 'admin',
      userName: '72345678',
      dni: '72345678',
      phone: '3644123456',
    },
    {
      id: nanoid(11),
      email: 'sara@email.com',
      name: 'Sara',
      lastName: 'Johnson',
      password: bcryptjs.hashSync('123456'),
      role: 'user',
      userName: '82345678',
      dni: '82345678',
      phone: '3644123456',
    },
    {
      id: nanoid(11),
      email: 'mike@email.com',
      name: 'Mike',
      lastName: 'Anderson',
      password: bcryptjs.hashSync('123456'),
      role: 'admin',
      userName: '92345678',
      dni: '92345678',
      phone: '3644123456',
    },
    {
      id: nanoid(11),
      email: 'lisa@email.com',
      name: 'Lisa',
      lastName: 'Brown',
      password: bcryptjs.hashSync('123456'),
      role: 'user',
      userName: '10345678',
      dni: '10345678',
      phone: '3644123456',
    },
    {
      id: nanoid(11),
      email: 'chris@email.com',
      name: 'Chris',
      lastName: 'Taylor',
      password: bcryptjs.hashSync('123456'),
      role: 'admin',
      userName: '11345678',
      dni: '11345678',
      phone: '3644123456',
    },
    {
      id: nanoid(11),
      email: 'jane@email.com',
      name: 'Jane',
      lastName: 'Martinez',
      password: bcryptjs.hashSync('123456'),
      role: 'user',
      userName: '12245678',
      dni: '12245678',
      phone: '3644123456',
    },
    {
      id: nanoid(11),
      email: 'david@email.com',
      name: 'David',
      lastName: 'Wilson',
      password: bcryptjs.hashSync('123456'),
      role: 'admin',
      userName: '13345678',
      dni: '13345678',
      phone: '3644123456',
    },
    {
      id: nanoid(11),
      email: 'amy@email.com',
      name: 'Amy',
      lastName: 'White',
      password: bcryptjs.hashSync('123456'),
      role: 'user',
      userName: '14345678',
      dni: '14345678',
      phone: '3644123456',
    },
  ],
  categories: [
    { id: undefined, name: 'smartphone' },
    { id: undefined, name: 'laptop' },
    { id: undefined, name: 'tablet' },
    { id: undefined, name: 'accessory' },
  ],
  brands: [
    {
      id: nanoid(),
      name: 'apple',
      slug: 'apple',
    },
    {
      id: nanoid(),
      name: 'samsung',
      slug: 'samsung',
    },
    {
      id: nanoid(),
      name: 'motorola',
      slug: 'motorola',
    },
    {
      id: nanoid(),
      name: 'hp',
      slug: 'hp',
    },
    {
      id: nanoid(),
      name: 'lenovo',
      slug: 'lenovo',
    },
    {
      id: nanoid(),
      name: 'google',
      slug: 'google',
    },
  ],
  products: [
    // {
    //   id: nanoid(),
    //   title: '',
    //   description: '',
    //   price: 0,
    //   images: [''],
    //   inStock: 1,
    //   slug: '',
    //   tags: [''],
    //   type: '',    // brand: '',
    // },
    {
      id: nanoid(),
      title: 'Google Pixel Tablet',
      description:
        'La Pixel Tablet de Google combina la potencia de un ordenador con la portabilidad de una tablet. Disfruta de una pantalla vívida, un rendimiento fluido y acceso a miles de aplicaciones de Google Play. Con una batería de 4000mAh de larga duración. Almacenamiento interno de hasta 256GB.',
      price: 599,
      images: [
        '01-pixel-tablet.png',
        '02-pixel-tablet.png',
        '03-pixel-tablet.png',
        '04-pixel-tablet.png',
      ],
      inStock: 15,
      slug: 'google_pixel_tablet',
      tags: ['tablet', 'android', 'google', 'pixel', 'high-end'],
      type: 'tablet',
      brand: 'google',
    },
    {
      id: nanoid(),
      title: 'Samsung Galaxy SmartTag 2',
      description:
        'Samsung Galaxy SmartTag, un dispositivo de rastreo compacto que ayuda a localizar objetos personales mediante la aplicación SmartThings. Alcance de hasta 120 metros con Bluetooth.',
      price: 29,
      images: [
        '01-galaxy-smarttag2.jpg',
        '02-galaxy-smarttag2.jpg',
        '03-galaxy-smarttag2.jpg',
      ],
      inStock: 20,
      slug: 'samsung_galaxy_smarttag_2',
      tags: ['accessory', 'samsung', 'smarttag', 'tracker', 'bluetooth'],
      type: 'accessory',
      brand: 'samsung',
    },
    {
      id: nanoid(),
      title: 'Apple AirTag',
      description:
        'Apple AirTag, dispositivo de rastreo compacto con tecnología de precisión ultrabanda ancha. Compatible con la aplicación Buscar y resistente al agua y polvo (IP67).',
      price: 29,
      images: ['00-airtag.jpeg'],
      inStock: 25,
      slug: 'apple_airtag',
      tags: ['accessory', 'apple', 'airtag', 'tracker', 'ultrawideband'],
      type: 'accessory',
      brand: 'apple',
    },
    {
      id: nanoid(),
      title: 'Samsung Galaxy Buds 3 Pro',
      description:
        'Auriculares Samsung Galaxy Buds 3 Pro con cancelación activa de ruido, sonido 360 Audio y hasta 18 horas de duración de batería con el estuche de carga. Resistente al agua (IPX7).',
      price: 199,
      images: [
        '01-galaxy-buds3-pro.jpg',
        '02-galaxy-buds3-pro.jpg',
        '03-galaxy-buds3-pro.jpg',
        '04-galaxy-buds3-pro.jpg',
        '05-galaxy-buds3-pro.jpg',
      ],
      inStock: 15,
      slug: 'samsung_galaxy_buds_pro',
      tags: ['accessory', 'samsung', 'buds', 'wireless', 'noise-canceling'],
      type: 'accessory',
      brand: 'samsung',
    },
    {
      id: nanoid(),
      title: 'Samsung Galaxy Watch 6',
      description:
        'Reloj inteligente Samsung Galaxy Watch 6 con pantalla AMOLED de 1.5 pulgadas, sensor de frecuencia cardíaca, monitoreo de actividad y seguimiento de sueño. Compatible con Android y resistente al agua.',
      price: 399,
      images: [
        '01-galaxy-watch7.jpg',
        '02-galaxy-watch7.jpg',
        '03-galaxy-watch7.jpg',
        '04-galaxy-watch7.jpg',
      ],
      inStock: 7,
      slug: 'samsung_galaxy_watch_6',
      tags: [
        'accessory',
        'samsung',
        'smartwatch',
        'watch',
        'health-monitoring',
      ],
      type: 'accessory',
      brand: 'google',
    },
    {
      id: nanoid(),
      title: 'Samsung Galaxy Z Fold 6',
      description:
        'Samsung Galaxy Z Fold 6 con pantalla plegable de 7.6 pulgadas, procesador Snapdragon 8 Gen 2, 12GB RAM y 512GB de almacenamiento. Ideal para multitarea y productividad.',
      price: 1899,
      images: [
        '01-z-fold-6.jpg',
        '02-z-fold-6.jpg',
        '03-z-fold-6.jpg',
        '04-z-fold-6.jpg',
        '05-z-fold-6.jpg',
      ],
      inStock: 5,
      slug: 'samsung_galaxy_z_fold_6',
      tags: ['smartphone', 'samsung', 'galaxy', 'z fold', 'foldable'],
      type: 'smartphone',
      brand: 'samsung',
    },
    {
      id: nanoid(),
      title: 'Samsung Galaxy Z Flip 6',
      description:
        'Samsung Galaxy Z Flip 6 con diseño compacto y pantalla flexible de 6.7 pulgadas. Equipado con Snapdragon 8 Gen 2, 8GB de RAM, y 256GB de almacenamiento.',
      price: 999,
      images: [
        '01-z-flip-6.jpg',
        '02-z-flip-6.jpg',
        '03-z-flip-6.jpg',
        '04-z-flip-6.jpg',
        '05-z-flip-6.jpg',
        '06-z-flip-6.jpg',
      ],
      inStock: 8,
      slug: 'samsung_galaxy_z_flip_6',
      tags: ['smartphone', 'samsung', 'galaxy', 'z flip', 'foldable'],
      type: 'smartphone',
      brand: 'samsung',
    },
    {
      id: nanoid(),
      title: 'Samsung Galaxy Tab S10 Ultra',
      description:
        'Samsung Galaxy Tab S10 Ultra de 12.4 pulgadas con pantalla Super AMOLED, Snapdragon 8 Gen 2, 8GB de RAM y 512GB de almacenamiento. Incluye S Pen.',
      price: 1099,
      images: [
        '01-samsung-tab-s10-ultra.jpg',
        '02-samsung-tab-s10-ultra.jpg',
        '03-samsung-tab-s10-ultra.jpg',
        '04-samsung-tab-s10-ultra.jpg',
        '05-samsung-tab-s10-ultra.jpg',
      ],
      inStock: 5,
      slug: 'samsung_galaxy_tab_s10_ultra',
      tags: ['tablet', 'samsung', 'galaxy', 'tab', 's9', 'plus'],
      type: 'tablet',
      brand: 'samsung',
    },
    {
      id: nanoid(),
      title: 'MacBook Pro 16" M3 Max',
      description:
        'Apple MacBook Pro de 16 pulgadas con chip M3 Max, 36GB RAM, almacenamiento SSD de 1TB y pantalla Retina de alta resolución. Ideal para creadores y desarrolladores.',
      price: 3499,
      images: [
        '01-macbook-pro-m3.jpeg',
        '02-macbook-pro-m3.jpeg',
        '03-macbook-pro-m3.jpeg',
        '04-macbook-pro-m3.jpeg',
        '05-macbook-pro-m3.jpeg',
        '06-macbook-pro-m3.jpeg',
      ],
      inStock: 3,
      slug: 'macbook_pro_16_m3_max',
      tags: ['laptop', 'macbook', 'apple', 'pro', 'm2'],
      type: 'laptop',
      brand: 'apple',
    },
    {
      id: nanoid(),
      title: 'iPad Pro 11" M2',
      description:
        'iPad Pro de 11 pulgadas con chip M2, 256GB de almacenamiento y pantalla Liquid Retina. Compatible con Apple Pencil (2ª generación) y Magic Keyboard.',
      price: 999,
      images: [
        '00-ipad-pro.webp',
        '01-ipad-pro-black.webp',
        '02-ipad-pro-black.webp',
        '03-ipad-pro-black.webp',
        '04-ipad-pro-display.webp',
      ],
      inStock: 6,
      slug: 'ipad_pro_11_m2',
      tags: ['tablet', 'ipad', 'apple', 'pro', 'm2'],
      type: 'tablet',
      brand: 'apple',
    },
    {
      id: nanoid(),
      title: 'Pixel 9 Pro Fold',
      description:
        'Pixel 9 Pro Fold porcelain, creado por Google. Google Pixel 9 Pro Fold: Procesador Tensor G2, 16GB de RAM, 256GB de almacenamiento. Cámara con zoom óptico súper suave y estabilización de video. ¡Sellado y listo para cualquier tarea!',
      price: 1799,
      images: [
        '01-pixel_fold.png',
        '02-pixel_fold.png',
        '03-pixel_fold.png',
        '04-pixel_fold.png',
      ],
      inStock: 4,
      slug: 'pixel_9_pro_fold-porcelain',
      tags: ['pixel', 'fold', 'porcelain', 'pro', 'google'],
      type: 'smartphone',
      brand: 'google',
    },
    {
      id: nanoid(),
      title: 'Pixel 9 Pro XL',
      description:
        'Smartphone Pixel 9 Pro XL, creado por Google. Google Pixel 9 Pro XL: Procesador Tensor G2, 16GB de RAM, 256GB de almacenamiento. Cámara con zoom óptico súper suave y estabilización de video. ¡Sellado y listo para cualquier tarea!',
      price: 1099,
      images: [
        '01-pixel_pro_xl.png',
        '02-pixel_pro_xl.png',
        '03-pixel_pro_xl.png',
        '04-pixel_pro_xl.png',
      ],
      inStock: 8,
      slug: 'pixel_pro_xl',
      tags: ['google', 'pixel', 'pro', 'xl'],
      type: 'smartphone',
      brand: 'google',
    },
    {
      id: nanoid(),
      title: 'Samsung Galaxy S24 Ultra',
      description:
        'Samsung Galaxy S24 Ultra, con un diseño elegante y una pantalla de alta resolución. Memoria interna: 512 GB | Procesador: Exynos 9610 (Octa-core) | Procesador de GPU: Adreno 640 | 12 GB de RAM | Batería de larga duración.',
      price: 1419,
      images: [
        '01-s24ultra.jpg',
        '02-s24ultra.jpg',
        '03-s24ultra.jpg',
        '04-s24ultra.jpg',
      ],
      inStock: 4,
      slug: 'samsung_galaxy_s24_ultra',
      tags: ['smartphone', 'samsung', 'galaxy', 's24', 'ultra'],
      type: 'smartphone',
      brand: 'samsung',
    },
    {
      id: nanoid(),
      title: 'Samsung Galaxy Book 5 Pro 360',
      description:
        'Laptop Samsung Galaxy Book 5 Pro 360 de alto rendimiento, con un diseño elegante y una pantalla de alta resolución. Procesador Intel Ultra 7 (Series 2) | 16 GB de RAM | 1 TB de almacenamiento (SSD) | Procesador de GPU | Batería de larga duración.',
      price: 1699,
      images: [
        '01-galaxy-book5.jpg',
        '02-galaxy-book5.jpg',
        '03-galaxy-book5.jpg',
        '04-galaxy-book5.jpg',
        '05-galaxy-book5.jpg',
        '06-galaxy-book5.jpg',
        '07-galaxy-book5.jpg',
      ],
      inStock: 1,
      slug: 'galaxy_book_5_pro_360',
      tags: ['samsung, laptop, galaxy, book'],
      type: 'laptop',
      brand: 'samsung',
    },
    {
      id: nanoid(),
      title: 'iPhone 16 Pro | 256GB - Blanco',
      description:
        'Diseño de titanio | Procesador A18 Pro | Pantalla 6.3" Super Retina | Cámara 48 MP | USB-C',
      images: [
        '01-iphone-16-pro-finish-select-202409-6-3inch-whitetitanium.webp',
        '02-iphone-16-pro-finish-select-202409-6-3inch-whitetitanium_AV1.webp',
        '04-iphone-16-pro-finish-select-202409-6-3inch-whitetitanium_AV3.webp',
      ],
      inStock: 4,
      price: 1000,
      slug: 'iphone-16-pro-256gb-blanco',
      tags: ['phone'],
      type: 'smartphone',
      brand: 'apple',
    },
    {
      id: nanoid(),
      title: 'Macbook Air M3 | 256GB - Midnight',
      description:
        'El MacBook Air M3 es la última generación de portátiles ultraligeros de Apple. Equipado con el nuevo chip M3, ofrece un rendimiento superior en un diseño delgado y elegante. Con 256GB de almacenamiento y acabado en color Midnight, este portátil es ideal tanto para profesionales como para estudiantes. Pantalla Retina de 13 pulgadas, batería de larga duración y diseño silencioso sin ventilador.',
      images: [
        '01-mba13-m3-midnight-gallery1-202402.jpeg',
        '02-mba13-m3-midnight-gallery2-202402.jpeg',
        '04-mba13-m3-midnight-gallery5-202402.jpeg',
      ],
      inStock: 2,
      price: 1200,
      slug: 'macbook-air-m3-256gb-midnight',
      tags: ['laptop'],
      type: 'laptop',
      brand: 'apple',
    },
    {
      id: nanoid(),
      title: 'Apple Pencil Puntas Extra Pack 4',
      description:
        'Set de 4 puntas extra para tu Apple Pencil. Compatible con Apple Pencil Pro, Apple Pencil (2ª generación), Apple Pencil (USB-C) y Apple Pencil (1ª generación). Fabricado por Apple.',
      images: ['00-AP_PENCIL_PUNTAS.jpeg'],
      inStock: 1,
      price: 60,
      slug: 'apple_pencil_puntas_extra-pack_4',
      tags: ['apple', 'apple_pencil'],
      type: 'accessory',
      brand: 'apple',
    },
    {
      id: nanoid(),
      title: 'Apple Pencil 2ª generación',
      description:
        'El Apple Pencil (2.ª generación) ofrece una precisión de píxel perfecta y una latencia baja líder en el sector, por lo que es ideal para dibujar, hacer bocetos, colorear, tomar notas, marcar PDF y mucho más. Y es tan fácil y natural de usar como un lápiz. | Apple Pencil (2.ª generación) también te permite cambiar de herramienta sin necesidad de dejarlo en el suelo, gracias a su superficie táctil intuitiva que admite el doble toque. Además, se empareja, se carga y se guarda magnéticamente en el lateral del iPad. | Apple Pencil (2.ª generación) es compatible con Apple Pencil hover cuando se utiliza con iPad Pro de 12,9 pulgadas (6.ª generación) y iPad Pro de 11 pulgadas (4.ª generación).',
      price: 129,
      images: ['01-AP_PENCIL_2.jpeg', '02-AP_PENCIL_2.jpeg'],
      inStock: 2,
      slug: 'apple_pencil_2da-generacion',
      tags: ['apple', 'apple_pencil'],
      type: 'accessory',
      brand: 'apple',
    },
    {
      id: nanoid(),
      title: 'Cable USB a Lightning - iPhone/iPad',
      description:
        'Este cable USB permite conectar tu dispositivo con conector Lightning a puerto USB de tu computadora, ideal para sincronizarlo y cargarlo. | Es compatible con iPhone 5 hasta iPhone 14.',
      price: 29,
      images: [
        '00-USB_A-to-LIGHTNING.jpeg',
        'LIGHTNING_ZOOM.jpeg',
        'USB_A-ZOOM.jpeg',
      ],
      inStock: 7,
      slug: 'cable_usb_a-to-lightning_iphone_ipad',
      tags: ['cable', 'usb', 'lightning'],
      type: 'accessory',
      brand: 'apple',
    },
    {
      id: nanoid(),
      title: 'Cable USB C a Lightning - iPhone/iPad',
      description:
        'Este cable USB C permite conectar tu dispositivo con conector Lightning a puertos modernos USB-C, altas velocidades y baja latencia, ideal para sincronizarlo y cargarlo. | Es compatible con cargadores USB-C de iPad y Macbook.',
      price: 44,
      images: ['00-USB_C-LIGHTNING.jpeg', 'LIGHTNING_ZOOM.jpeg'],
      inStock: 4,
      slug: 'cable_usb_c-a-lightning_iphone_ipad',
      tags: ['cable', 'usb', 'usb_c', 'lightning'],
      type: 'accessory',
      brand: 'apple',
    },
    {
      id: nanoid(),
      title: 'Cable USB-C a USB-C Apple',
      description:
        'Cable USB-C a USB-C Apple para conectar tu iPad y Macbook con cargadores USB-C.',
      price: 55,
      images: ['00-USB_C-USB_C.jpeg', 'USB_C-X2-ZOOM.jpeg'],
      inStock: 8,
      slug: 'cable-usb-c-a-usb-c-apple',
      tags: ['cable', 'usb-c', 'apple'],
      type: 'accessory',
      brand: 'apple',
    },
    {
      id: nanoid(),
      description:
        'Introducing the Tesla Chill Collection. The Men’s Chill Crew Neck Sweatshirt has a premium, heavyweight exterior and soft fleece interior for comfort in any season. The sweatshirt features a subtle thermoplastic polyurethane T logo on the chest and a Tesla wordmark below the back collar. Made from 60% cotton and 40% recycled polyester.',
      images: ['1740176-00-A_0_2000.jpg', '1740176-00-A_1.jpg'],
      inStock: 7,
      price: 75,
      slug: 'mens_chill_crew_neck_sweatshirt',
      type: 'smartphone',
      brand: 'apple',
      tags: ['sweatshirt'],
      title: 'Men’s Chill Crew Neck Sweatshirt',
    },
    {
      id: nanoid(),
      description:
        "The Men's Quilted Shirt Jacket features a uniquely fit, quilted design for warmth and mobility in cold weather seasons. With an overall street-smart aesthetic, the jacket features subtle silicone injected Tesla logos below the back collar and on the right sleeve, as well as custom matte metal zipper pulls. Made from 87% nylon and 13% polyurethane.",
      images: ['1740507-00-A_0_2000.jpg', '1740507-00-A_1.jpg'],
      inStock: 5,
      price: 200,
      slug: 'men_quilted_shirt_jacket',
      type: 'smartphone',
      brand: 'apple',
      tags: ['jacket'],
      title: "Men's Quilted Shirt Jacket",
    },
    {
      id: nanoid(),
      description:
        "Introducing the Tesla Raven Collection. The Men's Raven Lightweight Zip Up Bomber has a premium, modern silhouette made from a sustainable bamboo cotton blend for versatility in any season. The hoodie features subtle thermoplastic polyurethane Tesla logos on the left chest and below the back collar, a concealed chest pocket with custom matte zipper pulls and a french terry interior. Made from 70% bamboo and 30% cotton.",
      images: ['1740250-00-A_0_2000.jpg', '1740250-00-A_1.jpg'],
      inStock: 10,
      price: 130,
      slug: 'men_raven_lightweight_zip_up_bomber_jacket',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: "Men's Raven Lightweight Zip Up Bomber Jacket",
    },
    {
      id: nanoid(),
      description:
        "Introducing the Tesla Turbine Collection. Designed for style, comfort and everyday lifestyle, the Men's Turbine Long Sleeve Tee features a subtle, water-based T logo on the left chest and our Tesla wordmark below the back collar. The lightweight material is double-dyed, creating a soft, casual style for ideal wear in any season. Made from 50% cotton and 50% polyester.",
      images: ['1740280-00-A_0_2000.jpg', '1740280-00-A_1.jpg'],
      inStock: 50,
      price: 45,
      slug: 'men_turbine_long_sleeve_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: "Men's Turbine Long Sleeve Tee",
    },
    {
      id: nanoid(),
      description:
        "Introducing the Tesla Turbine Collection. Designed for style, comfort and everyday lifestyle, the Men's Turbine Short Sleeve Tee features a subtle, water-based Tesla wordmark across the chest and our T logo below the back collar. The lightweight material is double-dyed, creating a soft, casual style for ideal wear in any season. Made from 50% cotton and 50% polyester.",
      images: ['1741416-00-A_0_2000.jpg', '1741416-00-A_1.jpg'],
      inStock: 50,
      price: 40,
      slug: 'men_turbine_short_sleeve_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: "Men's Turbine Short Sleeve Tee",
    },
    {
      id: nanoid(),
      description:
        'Designed for comfort, the Cybertruck Owl Tee is made from 100% cotton and features our signature Cybertruck icon on the back.',
      images: ['7654393-00-A_2_2000.jpg', '7654393-00-A_3.jpg'],
      inStock: 0,
      price: 35,
      slug: 'men_cybertruck_owl_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: "Men's Cybertruck Owl Tee",
    },
    {
      id: nanoid(),
      description:
        "Inspired by our fully integrated home solar and storage system, the Tesla Solar Roof Tee advocates for clean, sustainable energy wherever you go. Designed for fit, comfort and style, the tee features an aerial view of our seamless Solar Roof design on the front with our signature T logo above 'Solar Roof' on the back. Made from 100% Peruvian cotton.",
      images: ['1703767-00-A_0_2000.jpg', '1703767-00-A_1.jpg'],
      inStock: 15,
      price: 35,
      slug: 'men_solar_roof_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: "Men's Solar Roof Tee",
    },
    {
      id: nanoid(),
      description:
        "Inspired by the world’s most unlimited resource, the Let the Sun Shine Tee highlights our fully integrated home solar and storage system. Designed for fit, comfort and style, the tee features a sunset graphic along with our Tesla wordmark on the front and our signature T logo printed above 'Solar Roof' on the back. Made from 100% Peruvian cotton.",
      images: ['1700280-00-A_0_2000.jpg', '1700280-00-A_1.jpg'],
      inStock: 17,
      price: 35,
      slug: 'men_let_the_sun_shine_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: "Men's Let the Sun Shine Tee",
    },
    {
      id: nanoid(),
      description:
        "Designed for fit, comfort and style, the Men's 3D Large Wordmark Tee is made from 100% Peruvian cotton with a 3D silicone-printed Tesla wordmark printed across the chest.",
      images: ['8764734-00-A_0_2000.jpg', '8764734-00-A_1.jpg'],
      inStock: 12,
      price: 35,
      slug: 'men_3d_large_wordmark_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: "Men's 3D Large Wordmark Tee",
    },
    {
      id: nanoid(),
      description:
        'Designed for fit, comfort and style, the Tesla T Logo Tee is made from 100% Peruvian cotton and features a silicone-printed T Logo on the left chest.',
      images: ['7652426-00-A_0_2000.jpg', '7652426-00-A_1.jpg'],
      inStock: 5,
      price: 35,
      slug: 'men_3d_t_logo_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: "Men's 3D T Logo Tee",
    },
    {
      id: nanoid(),
      description:
        'Designed for comfort and style in any size, the Tesla Small Wordmark Tee is made from 100% Peruvian cotton and features a 3D silicone-printed wordmark on the left chest.',
      images: ['8528839-00-A_0_2000.jpg', '8528839-00-A_2.jpg'],
      inStock: 2,
      price: 35,
      slug: 'men_3d_small_wordmark_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: 'Men’s 3D Small Wordmark Tee',
    },
    {
      id: nanoid(),
      description:
        "Designed to celebrate Tesla's incredible performance mode, the Plaid Mode Tee features great fit, comfort and style. Made from 100% cotton, it's the next best thing to riding shotgun at the Nürburgring.",
      images: ['1549268-00-A_0_2000.jpg', '1549268-00-A_2.jpg'],
      inStock: 82,
      price: 35,
      slug: 'men_plaid_mode_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: "Men's Plaid Mode Tee",
    },
    {
      id: nanoid(),
      description:
        "Inspired by our popular home battery, the Tesla Powerwall Tee is made from 100% cotton and features the phrase 'Pure Energy' under our signature logo in the back. Designed for fit, comfort and style, the exclusive tee promotes sustainable energy in any environment.",
      images: ['9877034-00-A_0_2000.jpg', '9877034-00-A_2.jpg'],
      inStock: 24,
      price: 35,
      slug: 'men_powerwall_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: "Men's Powerwall Tee",
    },
    {
      id: nanoid(),
      description:
        'Inspired by Tesla Battery Day and featuring the unveiled tabless battery cell, Battery Day Tee celebrates the future of energy storage and cell manufacturing. Designed for fit, comfort and style, Battery Day Tee is made from 100% cotton with a stylized cell printed across the chest. Made in Peru.',
      images: ['1633802-00-A_0_2000.jpg', '1633802-00-A_2.jpg'],
      inStock: 5,
      price: 30,
      slug: 'men_battery_day_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: "Men's Battery Day Tee",
    },
    {
      id: nanoid(),
      description:
        'Designed for exceptional comfort and inspired by the Cybertruck unveil event, the Cybertruck Bulletproof Tee is made from 100% cotton and features our signature Cybertruck icon on the back.',
      images: ['7654399-00-A_0_2000.jpg', '7654399-00-A_1.jpg'],
      inStock: 150,
      price: 30,
      slug: 'men_cybertruck_bulletproof_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: 'Men’s Cybertruck Bulletproof Tee',
    },
    {
      id: nanoid(),
      description:
        'Inspired by the Model Y order confirmation graphic, the limited edition Haha Yes Tee is designed for comfort and style. Made from 100% Peruvian cotton and featuring the Tesla wordmark across the chest, the exclusive tee will commemorate your order for years to come.',
      images: ['7652410-00-A_0.jpg', '7652410-00-A_1_2000.jpg'],
      inStock: 10,
      price: 35,
      slug: 'men_haha_yes_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: "Men's Haha Yes Tee",
    },
    {
      id: nanoid(),
      description:
        'Designed for fit, comfort and style, the limited edition S3XY Tee is made from 100% cotton with a 3D silicone-printed “S3XY” logo across the chest. Made in Peru. Available in black.',
      images: ['8764600-00-A_0_2000.jpg', '8764600-00-A_2.jpg'],
      inStock: 34,
      price: 35,
      slug: 'men_s3xy_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: "Men's S3XY Tee",
    },
    {
      id: nanoid(),
      description:
        "Designed for fit, comfort and style, the Men's 3D Wordmark Long Sleeve Tee is made from 100% cotton and features an understated wordmark logo on the left chest.",
      images: ['8764813-00-A_0_2000.jpg', '8764813-00-A_1.jpg'],
      inStock: 15,
      price: 40,
      slug: 'men_3d_wordmark_long_sleeve_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: "Men's 3D Wordmark Long Sleeve Tee",
    },
    {
      id: nanoid(),
      description:
        "Designed for fit, comfort and style, the Men's 3D T Logo Long Sleeve Tee is made from 100% cotton and features an understated T logo on the left chest.",
      images: ['8529198-00-A_0_2000.jpg', '8529198-00-A_1.jpg'],
      inStock: 12,
      price: 40,
      slug: 'men_3d_t_logo_long_sleeve_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: "Men's 3D T Logo Long Sleeve Tee",
    },
    {
      id: nanoid(),
      description:
        "Introducing the Tesla Raven Collection. The Men's Raven Lightweight Hoodie has a premium, relaxed silhouette made from a sustainable bamboo cotton blend. The hoodie features subtle thermoplastic polyurethane Tesla logos across the chest and on the sleeve with a french terry interior for versatility in any season. Made from 70% bamboo and 30% cotton.",
      images: ['1740245-00-A_0_2000.jpg', '1740245-00-A_1.jpg'],
      inStock: 10,
      price: 115,
      slug: 'men_raven_lightweight_hoodie',
      type: 'accessory',
      brand: 'apple',
      tags: ['hoodie'],
      title: "Men's Raven Lightweight Hoodie",
    },
    {
      id: nanoid(),
      description:
        'Introducing the Tesla Chill Collection. The Chill Pullover Hoodie has a premium, heavyweight exterior and soft fleece interior for comfort in any season. The unisex hoodie features subtle thermoplastic polyurethane Tesla logos across the chest and on the sleeve, a double layer single seam hood and pockets with custom matte zipper pulls. Made from 60% cotton and 40% recycled polyester.',
      images: ['1740051-00-A_0_2000.jpg', '1740051-00-A_1.jpg'],
      inStock: 10,
      price: 130,
      slug: 'chill_pullover_hoodie',
      type: 'accessory',
      brand: 'apple',
      tags: ['hoodie'],
      title: 'Chill Pullover Hoodie',
    },
    {
      id: nanoid(),
      description:
        "Introducing the Tesla Chill Collection. The Men's Chill Full Zip Hoodie has a premium, heavyweight exterior and soft fleece interior for comfort in any season. The hoodie features subtle thermoplastic polyurethane Tesla logos on the left chest and sleeve, a double layer single seam hood and pockets with custom matte zipper pulls. Made from 60% cotton and 40% recycled polyester.",
      images: ['1741111-00-A_0_2000.jpg', '1741111-00-A_1.jpg'],
      inStock: 100,
      price: 85,
      slug: 'men_chill_full_zip_hoodie',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: "Men's Chill Full Zip Hoodie",
    },
    {
      id: nanoid(),
      description:
        'Introducing the Tesla Chill Collection. The Men’s Chill Quarter Zip Pullover has a premium, heavyweight exterior and soft fleece interior for comfort in any season. The pullover features subtle thermoplastic polyurethane Tesla logos on the left chest and below the back collar, as well as a custom matte zipper pull. Made from 60% cotton and 40% recycled polyester.',
      images: ['1740140-00-A_0_2000.jpg', '1740140-00-A_1.jpg'],
      inStock: 7,
      price: 85,
      slug: 'men_chill_quarter_zip_pullover_-_gray',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: "Men's Chill Quarter Zip Pullover - Gray",
    },
    {
      id: nanoid(),
      description:
        'Introducing the Tesla Chill Collection. The Men’s Chill Quarter Zip Pullover has a premium, heavyweight exterior and soft fleece interior for comfort in any season. The pullover features subtle thermoplastic polyurethane Tesla logos on the left chest and below the back collar, as well as a custom matte zipper pull. Made from 60% cotton and 40% recycled polyester.',
      images: ['1740145-00-A_2_2000.jpg', '1740145-00-A_1.jpg'],
      inStock: 15,
      price: 85,
      slug: 'men_chill_quarter_zip_pullover_-_white',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: "Men's Chill Quarter Zip Pullover - White",
    },
    {
      id: nanoid(),
      description:
        'The Unisex 3D Large Wordmark Pullover Hoodie features soft fleece and an adjustable, jersey-lined hood for comfort and coverage. Designed in a unisex style, the pullover hoodie includes a tone-on-tone 3D silicone-printed wordmark across the chest.',
      images: ['8529107-00-A_0_2000.jpg', '8529107-00-A_1.jpg'],
      inStock: 15,
      price: 70,
      slug: '3d_large_wordmark_pullover_hoodie',
      type: 'accessory',
      brand: 'apple',
      tags: ['hoodie'],
      title: '3D Large Wordmark Pullover Hoodie',
    },
    {
      id: nanoid(),
      description:
        'As with the iconic Tesla logo, the Cybertruck Graffiti Hoodie is a classic in the making. Unisex style featuring soft fleece and an adjustable, jersey-lined hood for comfortable coverage.',
      images: ['7654420-00-A_0_2000.jpg', '7654420-00-A_1_2000.jpg'],
      inStock: 13,
      price: 60,
      slug: 'cybertruck_graffiti_hoodie',
      type: 'accessory',
      brand: 'apple',
      tags: ['hoodie'],
      title: 'Cybertruck Graffiti Hoodie',
    },
    {
      id: nanoid(),
      description:
        'The Relaxed T Logo Hat is a classic silhouette combined with modern details, featuring a 3D T logo and a custom metal buckle closure. The ultrasoft design is flexible and abrasion resistant, while the inner sweatband includes quilted padding for extra comfort and moisture wicking. The visor is fully made from recycled plastic bottles. 100% Cotton.',
      images: ['1657932-00-A_0_2000.jpg', '1657932-00-A_1.jpg'],
      inStock: 11,
      price: 30,
      slug: 'relaxed_t_logo_hat',
      type: 'laptop',
      brand: 'apple',
      tags: ['hats'],
      title: 'Relaxed T Logo Hat',
    },
    {
      id: nanoid(),
      description:
        'The Relaxed T Logo Hat is a classic silhouette combined with modern details, featuring a 3D T logo and a custom metal buckle closure. The ultrasoft design is flexible and abrasion resistant, while the inner sweatband includes quilted padding for extra comfort and moisture wicking. The visor is fully made from recycled plastic bottles. 100% Cotton.',
      images: ['1740417-00-A_0_2000.jpg', '1740417-00-A_1.jpg'],
      inStock: 13,
      price: 35,
      slug: 'thermal_cuffed_beanie',
      type: 'laptop',
      brand: 'apple',
      tags: ['hats'],
      title: 'Thermal Cuffed Beanie',
    },
    {
      id: nanoid(),
      description:
        "The Women's Cropped Puffer Jacket features a uniquely cropped silhouette for the perfect, modern style while on the go during the cozy season ahead. The puffer features subtle silicone injected Tesla logos below the back collar and on the right sleeve, custom matte metal zipper pulls and a soft, fleece lined collar. Made from 87% nylon and 13% polyurethane.",
      images: ['1740535-00-A_0_2000.jpg', '1740535-00-A_1.jpg'],
      inStock: 85,
      price: 225,
      slug: 'women_cropped_puffer_jacket',
      type: 'accessory',
      brand: 'apple',
      tags: ['hoodie'],
      title: "Women's Cropped Puffer Jacket",
    },
    {
      id: nanoid(),
      description:
        "Introducing the Tesla Chill Collection. The Women's Chill Half Zip Cropped Hoodie has a premium, soft fleece exterior and cropped silhouette for comfort in everyday lifestyle. The hoodie features an elastic hem that gathers at the waist, subtle thermoplastic polyurethane Tesla logos along the hood and on the sleeve, a double layer single seam hood and a custom ring zipper pull. Made from 60% cotton and 40% recycled polyester.",
      images: ['1740226-00-A_0_2000.jpg', '1740226-00-A_1.jpg'],
      inStock: 10,
      price: 130,
      slug: 'women_chill_half_zip_cropped_hoodie',
      type: 'accessory',
      brand: 'apple',
      tags: ['hoodie'],
      title: "Women's Chill Half Zip Cropped Hoodie",
    },
    {
      id: nanoid(),
      description:
        "Introducing the Tesla Raven Collection. The Women's Raven Slouchy Crew Sweatshirt has a premium, relaxed silhouette made from a sustainable bamboo cotton blend. The slouchy crew features a subtle thermoplastic polyurethane Tesla wordmark on the left sleeve and a french terry interior for a cozy look and feel in every season. Pair it with your Raven Joggers or favorite on the go fit. Made from 70% bamboo and 30% cotton.",
      images: ['1740260-00-A_0_2000.jpg', '1740260-00-A_1.jpg'],
      inStock: 9,
      price: 110,
      slug: 'women_raven_slouchy_crew_sweatshirt',
      type: 'accessory',
      brand: 'apple',
      tags: ['hoodie'],
      title: "Women's Raven Slouchy Crew Sweatshirt",
    },
    {
      id: nanoid(),
      description:
        "Introducing the Tesla Turbine Collection. Designed for style, comfort and everyday lifestyle, the Women's Turbine Cropped Long Sleeve Tee features a subtle, water-based Tesla wordmark across the chest and our T logo below the back collar. The lightweight material is double-dyed, creating a soft, casual style with a cropped silhouette. Made from 50% cotton and 50%",
      images: ['1740290-00-A_0_2000.jpg', '1740290-00-A_1.jpg'],
      inStock: 10,
      price: 45,
      slug: 'women_turbine_cropped_long_sleeve_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: "Women's Turbine Cropped Long Sleeve Tee",
    },
    {
      id: nanoid(),
      description:
        "ntroducing the Tesla Turbine Collection. Designed for style, comfort and everyday lifestyle, the Women's Turbine Cropped Short Sleeve Tee features a subtle, water-based Tesla wordmark across the chest and our T logo below the back collar. The lightweight material is double-dyed, creating a soft, casual style with a cropped silhouette. Made from 50% cotton and 50% polyester.",
      images: ['1741441-00-A_0_2000.jpg', '1741441-00-A_1.jpg'],
      inStock: 0,
      price: 40,
      slug: 'women_turbine_cropped_short_sleeve_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: "Women's Turbine Cropped Short Sleeve Tee",
    },
    {
      id: nanoid(),
      description:
        "Designed for style and comfort, the ultrasoft Women's T Logo Short Sleeve Scoop Neck Tee features a tonal 3D silicone-printed T logo on the left chest. Made of 50% Peruvian cotton and 50% Peruvian viscose.",
      images: ['8765090-00-A_0_2000.jpg', '8765090-00-A_1.jpg'],
      inStock: 30,
      price: 35,
      slug: 'women_t_logo_short_sleeve_scoop_neck_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: "Women's T Logo Short Sleeve Scoop Neck Tee",
    },
    {
      id: nanoid(),
      description:
        "Designed for style and comfort, the ultrasoft Women's T Logo Long Sleeve Scoop Neck Tee features a tonal 3D silicone-printed T logo on the left chest. Made of 50% Peruvian cotton and 50% Peruvian viscose.",
      images: ['8765100-00-A_0_2000.jpg', '8765100-00-A_1.jpg'],
      inStock: 16,
      price: 40,
      slug: 'women_t_logo_long_sleeve_scoop_neck_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: "Women's T Logo Long Sleeve Scoop Neck Tee",
    },
    {
      id: nanoid(),
      description:
        "Designed for style and comfort, the Women's Small Wordmark Short Sleeve V-Neck Tee features a tonal 3D silicone-printed wordmark on the left chest. Made of 100% Peruvian cotton.",
      images: ['8765120-00-A_0_2000.jpg', '8765120-00-A_1.jpg'],
      inStock: 18,
      price: 35,
      slug: 'women_small_wordmark_short_sleeve_v-neck_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: "Women's Small Wordmark Short Sleeve V-Neck Tee",
    },
    {
      id: nanoid(),
      description:
        "Designed for style and comfort, the Women's Large Wordmark Short Sleeve Crew Neck Tee features a tonal 3D silicone-printed wordmark across the chest. Made of 100% Peruvian pima cotton.",
      images: ['8765115-00-A_0_2000.jpg', '8765115-00-A_1.jpg'],
      inStock: 5,
      price: 35,
      slug: 'women_large_wordmark_short_sleeve_crew_neck_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: "Women's Large Wordmark Short Sleeve Crew Neck Tee",
    },
    {
      id: nanoid(),
      description:
        "Designed to celebrate Tesla's incredible performance mode, the Plaid Mode Tee features great fit, comfort and style. Made from 100% cotton, it's the next best thing to riding shotgun at the Nürburgring.",
      images: ['1549275-00-A_0_2000.jpg', '1549275-00-A_1.jpg'],
      inStock: 16,
      price: 35,
      slug: 'women_plaid_mode_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: "Women's Plaid Mode Tee",
    },
    {
      id: nanoid(),
      description:
        "Inspired by our popular home battery, the Tesla Powerwall Tee is made from 100% cotton and features the phrase 'Pure Energy' under our signature logo in the back. Designed for fit, comfort and style, the exclusive tee promotes sustainable energy in any",
      images: ['9877040-00-A_0_2000.jpg', '9877040-00-A_1.jpg'],
      inStock: 10,
      price: 130,
      slug: 'women_powerwall_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: 'Women’s Powerwall Tee',
    },
    {
      id: nanoid(),
      description:
        "Fully customized and uniquely styled, the Women's Corp Jacket features a silicone-printed 'T' logo on the left chest and prominent Tesla wordmark across the back.",
      images: ['5645680-00-A_0_2000.jpg', '5645680-00-A_3.jpg'],
      inStock: 3,
      price: 90,
      slug: 'women_corp_jacket',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: "Women's Corp Jacket",
    },
    {
      id: nanoid(),
      description:
        "Introducing the Tesla Raven Collection. The Women's Raven Joggers have a premium, relaxed silhouette made from a sustainable bamboo cotton blend. The joggers feature a subtle thermoplastic polyurethane Tesla wordmark and T logo and a french terry interior for a cozy look and feel in every season. Pair them with your Raven Slouchy Crew Sweatshirt, Raven Lightweight Zip Up Jacket or other favorite on the go fit. Made from 70% bamboo and 30% cotton.",
      images: ['1740270-00-A_0_2000.jpg', '1740270-00-A_1.jpg'],
      inStock: 162,
      price: 100,
      slug: 'women_raven_joggers',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: "Women's Raven Joggers",
    },
    {
      id: nanoid(),
      description:
        'Designed for fit, comfort and style, the Kids Cybertruck Graffiti Long Sleeve Tee features a water-based Cybertruck graffiti wordmark across the chest, a Tesla wordmark down the left arm and our signature T logo on the back collar. Made from 50% cotton and 50% polyester.',
      images: ['1742694-00-A_1_2000.jpg', '1742694-00-A_3.jpg'],
      inStock: 10,
      price: 30,
      slug: 'kids_cybertruck_long_sleeve_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: 'Kids Cybertruck Long Sleeve Tee',
    },
    {
      id: nanoid(),
      description:
        'The Kids Scribble T Logo Tee is made from 100% Peruvian cotton and features a Tesla T sketched logo for every young artist to wear.',
      images: ['8529312-00-A_0_2000.jpg', '8529312-00-A_1.jpg'],
      inStock: 0,
      price: 25,
      slug: 'kids_scribble_t_logo_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: 'Kids Scribble T Logo Tee',
    },
    {
      id: nanoid(),
      description:
        'The Kids Cybertruck Tee features the iconic Cybertruck graffiti wordmark and is made from 100% Peruvian cotton for maximum comfort.',
      images: ['8529342-00-A_0_2000.jpg', '8529342-00-A_1.jpg'],
      inStock: 10,
      price: 25,
      slug: 'kids_cybertruck_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: 'Kids Cybertruck Tee',
    },
    {
      id: nanoid(),
      description:
        "The refreshed Kids Racing Stripe Tee is made from 100% Peruvian cotton, featuring a newly enhanced racing stripe with a brushed Tesla wordmark that's perfect for any speed racer.",
      images: ['8529354-00-A_0_2000.jpg', '8529354-00-A_1.jpg'],
      inStock: 10,
      price: 30,
      slug: 'kids_racing_stripe_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: 'Kids Racing Stripe Tee',
    },
    {
      id: nanoid(),
      description:
        'Designed for fit, comfort and style, the Tesla T Logo Tee is made from 100% Peruvian cotton and features a silicone-printed T Logo on the left chest.',
      images: ['7652465-00-A_0_2000.jpg', '7652465-00-A_1.jpg'],
      inStock: 10,
      price: 30,
      slug: 'kids_3d_t_logo_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: 'Kids 3D T Logo Tee',
    },
    {
      id: nanoid(),
      description:
        'The checkered tee is made from long grain, GMO free Peruvian cotton. Peru is the only country in the world where cotton is picked by hand on a large scale. The 4,500-year-old tradition prevents damage to the fiber during the picking process and removes the need to use chemicals to open the cotton plants before harvest. This environmentally friendly process results in cotton that is soft, strong, and lustrous – and the tee will get even softer with every wash.',
      images: ['100042307_0_2000.jpg', '100042307_alt_2000.jpg'],
      inStock: 10,
      price: 30,
      slug: 'kids_checkered_tee',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: 'Kids Checkered Tee',
    },
    {
      id: nanoid(),
      description:
        'For the future space traveler with discerning taste, a soft, cotton onesie with snap closure bottom. Clear labeling provided in case of contact with a new spacefaring civilization. 100% Cotton. Made in Peru',
      images: ['1473809-00-A_1_2000.jpg', '1473809-00-A_alt.jpg'],
      inStock: 16,
      price: 25,
      slug: 'made_on_earth_by_humans_onesie',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: 'Made on Earth by Humans Onesie',
    },
    {
      id: nanoid(),
      description:
        'The Kids Scribble T Logo Onesie is made from 100% Peruvian cotton and features a Tesla T sketched logo for every little artist to wear.',
      images: ['8529387-00-A_0_2000.jpg', '8529387-00-A_1.jpg'],
      inStock: 0,
      price: 30,
      slug: 'scribble_t_logo_onesie',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: 'Scribble T Logo Onesie',
    },
    {
      id: nanoid(),
      description:
        'Show your commitment to sustainable energy with this cheeky onesie for your young one. Note: Does not prevent emissions. 100% Cotton. Made in Peru.',
      images: ['1473834-00-A_2_2000.jpg', '1473829-00-A_2_2000.jpg'],
      inStock: 10,
      price: 30,
      slug: 'zero_emissions_(almost)_onesie',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: 'Zero Emissions (Almost) Onesie',
    },
    {
      id: nanoid(),
      description:
        'Wear your Kids Cyberquad Bomber Jacket during your adventures on Cyberquad for Kids. The bomber jacket features a graffiti-style illustration of our Cyberquad silhouette and wordmark. With three zippered pockets and our signature T logo and Tesla wordmark printed along the sleeves, Kids Cyberquad Bomber Jacket is perfect for wherever the trail takes you. Made from 60% cotton and 40% polyester.',
      images: ['1742702-00-A_0_2000.jpg', '1742702-00-A_1.jpg'],
      inStock: 10,
      price: 65,
      slug: 'kids_cyberquad_bomber_jacket',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: 'Kids Cyberquad Bomber Jacket',
    },
    {
      id: nanoid(),
      description:
        'Cruise the playground in style with the Kids Corp Jacket. Modeled after the original Tesla Corp Jacket, the Kids Corp Jacket features the same understated style and high-quality materials but at a pint-sized scale.',
      images: ['1506211-00-A_0_2000.jpg', '1506211-00-A_1_2000.jpg'],
      inStock: 10,
      price: 30,
      slug: 'kids_corp_jacket',
      type: 'smartphone',
      brand: 'apple',
      tags: ['shirt'],
      title: 'Kids Corp Jacket',
    },
  ],
};
